theme: jekyll-theme-cayman

# Group Movement
I am [Yessica Servin Dominguez](https://www.linkedin.com/in/yessica-servin-dominguez-663175165/), student of the [Bachelor’s Degree in
Video Games by UPC at CITM]( https://www.citm.upc.edu/ing/estudis/graus-videojocs/). 
This content is generated for the second year’s subject Project 2, under supervision of lecturer [Ricard Pillosu](https://es.linkedin.com/in/ricardpillosu).
